// Generated by CoffeeScript 1.4.0
/*
    @author DPR http://davidpaulrosser.co.uk
*/

var nodes, stylus;

stylus = require('stylus');

nodes = stylus.nodes;

/*
*   Adds default behavior to the url function
*
*   @param  String url
*   @return Literal
*/


exports.url = function(url) {
  return new nodes.Literal('url(' + new nodes.String(url.val) + ')');
};

/*
*   Remove the 'e' constant expression from a floating point number
*   
*   @param  Float num
*   @return Unit
*/


exports.removeConstE = function(num) {
  var index, result, str;
  str = String(num.val);
  index = str.indexOf('e-');
  result = null;
  if (index !== -1) {
    result = str.substr(0, index);
  } else {
    result = num.val;
  }
  return new nodes.Unit(parseFloat(result));
};
